# Generated by Django 3.1.3 on 2021-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_receipt_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
