# Generated by Django 3.1.3 on 2020-11-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_category_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
