# Generated by Django 3.1.3 on 2021-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_merchant_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
