# Generated by Django 3.1.3 on 2020-11-05 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_user_is_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 5, 6, 1, 57, 62791, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
