# Generated by Django 3.1.3 on 2020-11-06 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_order_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='qr_code',
            field=models.ImageField(upload_to='QR'),
        ),
        migrations.CreateModel(
            name='ScannedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
