# Generated by Django 3.1.3 on 2020-11-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_aboutus_contactus_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='conditions',
            new_name='content',
        ),
    ]
