# Generated by Django 3.1.3 on 2020-11-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20201109_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='policy_in_arabic',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='conditions_in_arabic',
        ),
    ]
