# Generated by Django 3.1.3 on 2020-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20201117_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='products',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
