# Generated by Django 3.1.3 on 2020-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20201117_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
