# Generated by Django 3.1.3 on 2020-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_receipt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
