# Generated by Django 3.1.3 on 2020-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20201119_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=''),
        ),
    ]
