# Generated by Django 3.1.3 on 2020-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20201124_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=300)),
                ('question_in_arabic', models.CharField(default='question', max_length=300)),
                ('answer', models.TextField()),
                ('answer_in_arabic', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
