# Generated by Django 3.1.3 on 2020-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_auto_20201209_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content_in_arabic',
            field=models.TextField(default='arbic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='conditions_in_arabic',
            field=models.TextField(default='aranbci'),
            preserve_default=False,
        ),
    ]
