# Generated by Django 3.1.3 on 2021-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_merchant_commercial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
