# Generated by Django 3.1.3 on 2021-01-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_orderitem_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=18),
        ),
    ]
