# Generated by Django 3.1.3 on 2021-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_auto_20210107_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
