# Generated by Django 3.1.3 on 2021-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_receipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
