# Generated by Django 3.1.3 on 2021-01-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_auto_20210118_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=2000)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.merchant')),
            ],
        ),
    ]
