# Generated by Django 3.1.3 on 2021-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_auto_20210118_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='address',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='merchant',
            new_name='merchant_name',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='branch',
            name='landmark',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='branch',
            name='street',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
