# Generated by Django 3.1.3 on 2021-01-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_auto_20210118_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='block',
            new_name='shop_no',
        ),
    ]
