# Generated by Django 3.1.3 on 2021-01-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0031_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_9',
        ),
    ]
