# Generated by Django 3.1.3 on 2021-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_auto_20210121_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='user',
        ),
    ]
