# Generated by Django 3.1.3 on 2021-01-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_remove_banner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_merchant', models.BooleanField(default=False)),
                ('can_manage_category', models.BooleanField(default=False)),
                ('can_manage_branch', models.BooleanField(default=False)),
                ('can_manage_receipts', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
