# Generated by Django 3.1.3 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0034_subadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='can_manage_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
