# Generated by Django 3.1.3 on 2021-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_subadmin_can_manage_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_receipts',
            field=models.BooleanField(default=False),
        ),
    ]
