# Generated by Django 3.1.3 on 2021-02-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='vat',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
