# Generated by Django 3.1.3 on 2021-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_auto_20210201_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='vat_percent',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
