# Generated by Django 3.1.3 on 2021-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0040_receipt_vat_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='vat_percent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
